"""Observer protocol versions. Independent of event schema and runner config."""

from __future__ import annotations

from typing import Final

OBSERVER_PROTOCOL_VERSION: Final[str] = "observer-protocol-v1"
OBSERVER_LAYOUT_SCHEMA_VERSION: Final[str] = "observer-layout-v1"
DEFAULT_LAYOUT_ID: Final[str] = "reference-v1"

SEMANTIC_EVENT_TYPES: Final[tuple[str, ...]] = (
    "AGENT_MOVED",
    "AGENT_SEARCHED",
    "AGENT_TOOK_ITEM",
    "AGENT_DROPPED_ITEM",
    "AGENT_GAVE_ITEM",
    "AGENT_ATE_ITEM",
    "AGENT_DRANK",
    "AGENT_SLEPT",
    "AGENT_TALKED",
    "AGENT_ASKED",
    "AGENT_TOLD",
    "AGENT_HELPED",
    "AGENT_ATTACKED",
    "AGENT_FLED",
    "AGENT_WAITED",
    "WEATHER_CHANGED",
    "RESOURCE_REGENERATED",
    "NEEDS_APPLIED",
    "EXPOSURE_APPLIED",
    "AGENT_DIED",
    "RESOURCE_HARVESTED",
    "CRAFT_STARTED",
    "ITEM_CRAFTED",
    "STRUCTURE_BUILT",
    "STRUCTURE_REPAIRED",
    "ITEM_STORED",
    "SEASON_CHANGED",
    "TEMPERATURE_BAND_CHANGED",
    "RESOURCE_NODE_DEPLETED",
    "RESOURCE_NODE_RECOVERED",
    "ENVIRONMENTAL_HAZARD_STARTED",
    "ENVIRONMENTAL_HAZARD_ENDED",
    "ARTIFACT_CREATED",
    "ARTIFACT_MODIFIED",
    "ARTIFACT_MOVED",
    "ARTIFACT_DESTROYED",
    "ARTIFACT_COPIED",
    "ARTIFACT_ANNOTATED",
    "ARTIFACT_DAMAGED",
    "ARTIFACT_PARTIALLY_LOST",
    "AGENT_CREATED",
    "AGENT_ENTERED_WORLD",
    "AGENT_INITIALIZED",
    "LIFECYCLE_STAGE_CHANGED",
    "KINSHIP_EDGE_RECORDED",
    "AGENT_FED",
    "AGENT_TRANSPORTED",
    "REPOSITORY_ESTABLISHED",
    "REPOSITORY_MEMBER_DEPOSITED",
    "REPOSITORY_MEMBER_RETRIEVED",
    "REPOSITORY_MAINTAINED",
    "REPOSITORY_INDEXED",
    "REPOSITORY_NEGLECTED",
    "EXPERIMENT_RESOLVED",
    "CORPSE_CUSTODY_OPENED",
    "AGENT_TOOK_FROM_CORPSE",
    "POSSESSION_CLAIM_ASSERTED",
)

SEMANTIC_TYPE_BY_KIND: Final[dict[str, str]] = {
    "move": "AGENT_MOVED",
    "search": "AGENT_SEARCHED",
    "take": "AGENT_TOOK_ITEM",
    "drop": "AGENT_DROPPED_ITEM",
    "give": "AGENT_GAVE_ITEM",
    "eat": "AGENT_ATE_ITEM",
    "drink": "AGENT_DRANK",
    "sleep": "AGENT_SLEPT",
    "talk": "AGENT_TALKED",
    "ask": "AGENT_ASKED",
    "tell": "AGENT_TOLD",
    "help": "AGENT_HELPED",
    "attack": "AGENT_ATTACKED",
    "flee": "AGENT_FLED",
    "wait": "AGENT_WAITED",
    "weather_changed": "WEATHER_CHANGED",
    "resource_regenerated": "RESOURCE_REGENERATED",
    "needs_applied": "NEEDS_APPLIED",
    "exposure_applied": "EXPOSURE_APPLIED",
    "died": "AGENT_DIED",
    "resource_harvested": "RESOURCE_HARVESTED",
    "craft_started": "CRAFT_STARTED",
    "item_crafted": "ITEM_CRAFTED",
    "structure_built": "STRUCTURE_BUILT",
    "structure_repaired": "STRUCTURE_REPAIRED",
    "item_stored": "ITEM_STORED",
    "season_changed": "SEASON_CHANGED",
    "temperature_band_changed": "TEMPERATURE_BAND_CHANGED",
    "resource_node_depleted": "RESOURCE_NODE_DEPLETED",
    "resource_node_recovered": "RESOURCE_NODE_RECOVERED",
    "environmental_hazard_started": "ENVIRONMENTAL_HAZARD_STARTED",
    "environmental_hazard_ended": "ENVIRONMENTAL_HAZARD_ENDED",
    "artifact_created": "ARTIFACT_CREATED",
    "artifact_modified": "ARTIFACT_MODIFIED",
    "artifact_moved": "ARTIFACT_MOVED",
    "artifact_destroyed": "ARTIFACT_DESTROYED",
    "artifact_copied": "ARTIFACT_COPIED",
    "artifact_annotated": "ARTIFACT_ANNOTATED",
    "artifact_damaged": "ARTIFACT_DAMAGED",
    "artifact_partially_lost": "ARTIFACT_PARTIALLY_LOST",
    "agent_created": "AGENT_CREATED",
    "agent_entered_world": "AGENT_ENTERED_WORLD",
    "agent_initialization_recorded": "AGENT_INITIALIZED",
    "lifecycle_stage_changed": "LIFECYCLE_STAGE_CHANGED",
    "kinship_edge_recorded": "KINSHIP_EDGE_RECORDED",
    "feed": "AGENT_FED",
    "transport": "AGENT_TRANSPORTED",
    "repository_established": "REPOSITORY_ESTABLISHED",
    "repository_member_deposited": "REPOSITORY_MEMBER_DEPOSITED",
    "repository_member_retrieved": "REPOSITORY_MEMBER_RETRIEVED",
    "repository_maintained": "REPOSITORY_MAINTAINED",
    "repository_indexed": "REPOSITORY_INDEXED",
    "repository_neglected": "REPOSITORY_NEGLECTED",
    "experiment_resolved": "EXPERIMENT_RESOLVED",
    "corpse_custody_opened": "CORPSE_CUSTODY_OPENED",
    "taken_from_corpse": "AGENT_TOOK_FROM_CORPSE",
    "possession_claim_asserted": "POSSESSION_CLAIM_ASSERTED",
}

RELATIONSHIP_DIMENSION_CODES: Final[tuple[str, ...]] = (
    "trust",
    "fear",
    "affection",
    "debt",
    "respect",
    "resentment",
    "familiarity",
    "dependency",
)

__all__ = [
    "DEFAULT_LAYOUT_ID",
    "OBSERVER_LAYOUT_SCHEMA_VERSION",
    "OBSERVER_PROTOCOL_VERSION",
    "RELATIONSHIP_DIMENSION_CODES",
    "SEMANTIC_EVENT_TYPES",
    "SEMANTIC_TYPE_BY_KIND",
]
