"""Authoritative world state and agent-facing contracts.

Public facade. Private authority modules (``world._*``) and legacy gateway
helpers are not re-exported. Objective mutation goes through ``simulation.WorldEngine``.
"""

from world.actions import (
    ActionProposal,
    ActionRequest,
    AgentCommand,
    Ask,
    Attack,
    Drink,
    Drop,
    Eat,
    Flee,
    Give,
    Help,
    Move,
    Search,
    Sleep,
    Take,
    Talk,
    Tell,
    Wait,
    require_agent_command,
)
from world.events import (
    Asked,
    Attacked,
    Dropped,
    Drunk,
    Eaten,
    EventDetails,
    Fled,
    Given,
    Helped,
    Moved,
    Searched,
    Slept,
    Taken,
    Talked,
    Told,
    Waited,
    WorldEvent,
)
from world.identifiers import (
    EntityId,
    EventId,
    ProposalId,
    RequestId,
    WorldId,
    WorldRevision,
)
from world.models import AgentBody, Item, LifeStatus, Location, Resource, Weather
from world.observations import Observation, detached_mapping
from world.values import (
    Fatigue,
    Health,
    Hunger,
    TemperatureCelsius,
    Thirst,
)

__all__ = [
    "ActionProposal",
    "ActionRequest",
    "AgentBody",
    "AgentCommand",
    "Ask",
    "Asked",
    "Attack",
    "Attacked",
    "Drink",
    "Drop",
    "Dropped",
    "Drunk",
    "Eat",
    "Eaten",
    "EntityId",
    "EventDetails",
    "EventId",
    "Fatigue",
    "Fled",
    "Flee",
    "Give",
    "Given",
    "Health",
    "Help",
    "Helped",
    "Hunger",
    "Item",
    "LifeStatus",
    "Location",
    "Move",
    "Moved",
    "Observation",
    "ProposalId",
    "RequestId",
    "Resource",
    "Search",
    "Searched",
    "Sleep",
    "Slept",
    "Take",
    "Taken",
    "Talk",
    "Talked",
    "Tell",
    "TemperatureCelsius",
    "Thirst",
    "Told",
    "Wait",
    "Waited",
    "Weather",
    "WorldEvent",
    "WorldId",
    "WorldRevision",
    "detached_mapping",
    "require_agent_command",
]
