"""Reusable test doubles for network-free unit tests."""

from tests.fakes.cognition import (
    FakeCognitionCallRecord,
    FakeCognitionFailureCode,
    FakeCognitionHarnessError,
    FakeFutureImagination,
    FakeIntentionSelector,
    FakeMemoryRetriever,
    FakeMemoryUpdateHook,
    FakeMotivationEvaluator,
    FakePerceptionInterpreter,
    FakePlanner,
    FakeSelfStateProjector,
    FakeSituationModeler,
    ScriptedStageFailure,
    ScriptedStageSuccess,
    bind_invocation,
    clear_invocation,
    invocation_context,
)
from tests.fakes.llm import (
    FakeCallRecord,
    FakeClock,
    FakeLLMFailureCode,
    FakeLLMProvider,
    FakeLLMProviderError,
    ScriptedFailure,
    ScriptedSuccess,
)
from tests.fakes.memory import FakeMemoryCallRecord, FakeMemoryService

__all__ = [
    "FakeCallRecord",
    "FakeClock",
    "FakeCognitionCallRecord",
    "FakeCognitionFailureCode",
    "FakeCognitionHarnessError",
    "FakeFutureImagination",
    "FakeIntentionSelector",
    "FakeLLMFailureCode",
    "FakeLLMProvider",
    "FakeLLMProviderError",
    "FakeMemoryCallRecord",
    "FakeMemoryRetriever",
    "FakeMemoryService",
    "FakeMemoryUpdateHook",
    "FakeMotivationEvaluator",
    "FakePerceptionInterpreter",
    "FakePlanner",
    "FakeSelfStateProjector",
    "FakeSituationModeler",
    "ScriptedFailure",
    "ScriptedStageFailure",
    "ScriptedStageSuccess",
    "ScriptedSuccess",
    "bind_invocation",
    "clear_invocation",
    "invocation_context",
]
